### PR TITLE
Implement a new command API

### PR DESCRIPTION
**Pull request by portlek**

### CODE REVIEW

**Comment by Admicos** [comment]
I was about to pull this, but I'll just wait until you implement the rest of the new command API in this PR.

**Comment by portlek** [comment]
yes, i will finish this pr in 1 or 2 days

**Comment by Admicos** [comment]
Gotcha. Also, while I'm ok with Cactoos, please make sure to keep dependencies at a minimum wherever you can. We don't want a huge jar file.

**Comment by portlek** [comment]
You need to create each argument piece by piece. like in the last commit;
https://github.com/okyanus-mc/api/pull/5/files#diff-446764ba6c54cbc2b49fa4af550e8122R31

**Comment by portlek** [comment]
It looks like complicated too. but it is more safety than before.

**Comment by portlek** [comment]
I just created the command which has main command, help argument and message argument in 1 min, I think this template is nice for now.

**Comment by Admicos** [comment]
Looks interesting. Is there any support for regular arguments, like we do with [CommandBuilder.arg](https://okyanus-mc.github.io/api/club/issizler/okyanus/api/cmd/CommandBuilder.html#arg-java.lang.String-club.issizler.okyanus.api.cmd.ArgumentType-boolean-) or have you just not implemented that yet?

**Comment by portlek** [comment]
yes it has. actually, the command can be a sub-command too, /core is a command and also help is a command in /core help, cause of, you can give runnable to each part of command, /core and /core help.
command is actually a runnable and requireble thing.

**Comment by Admicos** [comment]
Instead of using MinMaxReq, we might want to register the command arguments explicitly, like we do now. This will have the advantage of allowing tab completion with Brigadier.

Also, having both permission() and PermissionReq sounds like duplication. We should preferably only have one obvious way to do something.

**Comment by portlek** [comment]
> Instead of using MinMaxReq, we might want to register the command arguments explicitly, like we do now. This will have the advantage of allowing tab completion with Brigadier.
- hm yes. to that the developer must create all parts of the command with arguments. MinMax is unnecessary thing actually. i can remove it.

> Also, having both permission() and PermissionReq sounds like duplication. We should preferably only have one obvious way to do something.
- actually permission(#string) is PermissionReq.
```java
    public static CommandOption permission(String permission) {
        return new CommandOption(OptionType.REQUIREMENTS, new PermissionReq(permission));
    }
```
the developer might not want to use requirement just for permission.

**Comment by Admicos** [comment]
I posted about your possible changes in a couple places, and the responses I got were a little mixed, but leaning towards to preferring the old API

I also got a suggestion to just use Brigadier (https://github.com/Mojang/brigadier) itself, which is also a interesting.

**Comment by portlek** [comment]
we can give a change for now i think. maybe after i finish the newcmd package we can compare brigadier and the api. after comparing we can choose the best for the api

**Comment by Admicos** [comment]
I'm writing this before you've finished because I don't want any more of your time to go to waste. We should really decide on if we should roll our own API before doing it

**Comment by portlek** [comment]
you're right, it's fine for me. for using, i'm not sure for developer i think, it looks different;
```java
CommandDispatcher<CommandSourceStack> dispatcher = new CommandDispatcher<>();

dispatcher.register(
    literal("foo")
        .then(
            argument("bar", integer())
                .executes(c -> {
                    System.out.println("Bar is " + getInteger(c, "bar"));
                    return 1;
                })
        )
        .executes(c -> {
            System.out.println("Called foo with no arguments");
            return 1;
        })
);
```

**Comment by Admicos** [comment]
The advantages of Brigadier:

  * Used by MC internally, easier to implement for us
  * Less code for us to maintain

Disadvantages of Brigadier:

  * API isn't as elegant as I would've wanted
  * Stuff like permissions might need to be checked in the .executes methods manually

I'm really not sure on what to pick right now, your input?

**Comment by portlek** [comment]
i think, we need to choose the command framework after finish ours. now we just try/test the brigadier.

**Comment by portlek** [comment]
but my choose is allways ours, because it's;
- original
- ours
- easy to understand
- easy to create command without any documentation

**Comment by portlek** [comment]
I think, our goal must be, for all api;
- easy to understand 
- easy to use with docs. as less as possible

**Comment by Admicos** [comment]
Yeah, both of our APIs look easier than Brigadier, that's true.

**Comment by portlek** [comment]
a developer which want to pull request must understand our command api not like that;
https://github.com/Mojang/brigadier/blob/master/src/main/java/com/mojang/brigadier/CommandDispatcher.java#L205
this is a horrible thing that can't understandable

**Comment by portlek** [comment]
also there are good things for our api;
https://github.com/Mojang/brigadier/blob/master/src/main/java/com/mojang/brigadier/arguments/StringArgumentType.java
we can use this method to define argument types, it can be helpfull on tab-completation

**Comment by Admicos** [comment]
Internally, we'll have to convert our representation to Brigadier anyway. So using something closer to Brigadier will certainly help with that conversion.

**Comment by portlek** [comment]
their using like ChatComponent/json logic.
```
{
    commandLabel: "core",
    requirements: {
        ...: {}
        ...: {}
    }
    run : {}
    ...
    ...
}
```
i can use that logic in our api i guess.

**Comment by Admicos** [comment]
You can check out https://github.com/okyanus-mc/runtime/blob/master/src/main/java/club/issizler/okyanus/runtime/command/CommandRegistrar.java#L29 on how we currently register our builder based commands into Minecraft's brigadier.

**Comment by portlek** [comment]
```java
public void brigadiercmd() {
    CommandDispatcher dispatcher = new CommandDispatcher<CommandTest>();

    dispatcher.register(
        LiteralArgumentBuilder.literal("core")
            .then(
                RequiredArgumentBuilder.argument("help", StringArgumentType.string()
                ).executes(context -> {
                    // /core help executed!
                    return 0;
                })
            ).executes(context -> {
                // /core executed!
                return 0;
        })
    );
}
```
i upload the brigaider to the project and i can say it's complicating the code for developer. also we can't use import static for class, i don't know why.

**Comment by Admicos** [comment]
We shouldn't need Brigadier on the API as I thought we settled on using a custom API.

We'll only need it in the runtime, to convert commands into their Minecraft representations.

---

also, would you mind checking out #7 ?

**Comment by portlek** [comment]
> We shouldn't need Brigadier on the API as I thought we settled on using a custom API.
> 
> We'll only need it in the runtime, to convert commands into their Minecraft representations.
> 
- I just tested it.
> also, would you mind checking out #7 ?
- I'll

**Pull request closed without merging**
