### PR TITLE
Mod branch

### PR DESCRIPTION
**Pull request by portlek**
#include new command api.

### CODE REVIEW

**Comment by portlek** [comment]
it didn't create a new branch except cmd api :/

**Comment by Admicos** [comment]
Oh well. I'm planning to squash your commits before merging anyways, so it'll all end up in a single commit after you're done. 

So that shouldn't be a problem right now.

**Comment by Admicos** [comment]
Oh, just so you know, we **cannot** use constructor paramters on Mod classes. Our constructors need to have no paramters. Which is a Fabric loader requirement.

**Comment by portlek** [comment]
It can be possible

**Comment by portlek** [comment]
Anyway, just for Server class we can use singelton or we stuck this problem. Bukkit way:
https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/Bukkit.java#L63

**Comment by Admicos** [comment]
I really don't think we need a global Okyanus class. Server should manage it's own instance IMO. Especially if it's a singleton. If you have any other reason than "Bukkit does it", I'd love to hear it

**Comment by portlek** [comment]
Not just for 'bukkit does it', actually I don't want to write getInstance method to Server.interface like before

**Comment by portlek** [comment]
i felt this branch is going to weird/wrong place so, i close it for now.

**Comment by Admicos** [comment]
Why, exactly?

**Comment by portlek** [comment]
> Why, exactly?

Commands, players, servers things are very complicated for begining, its need a plan so, i need to think about the design of the api

**Comment by Admicos** [comment]
Alright. I'll just keep adding little things here and there until you finish your plan.

**Comment by Admicos** [comment]
ps: We might want to move fast, add functionality until we get to a proper beta, before starting to pay off our technical debt (refactor into a better state).

**Pull request closed without merging**
